# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e669b00d278f99ab6560321a2cc3b03dfe0f83986daf19bc8debb9f8176b8e0b2aac9e3a9cf684283978fb4531df03a08aade49522af367965de84fd8ebaebc2

test:
  secret_key_base: e73eee1b19f29db9067c01457d1e3e128e4996f77d20208ed30508abdff11d8a4becf861c91b4006b7d1e97c49746eadca406ccd6fbf2728916eb4d60ad96646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
